config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root "blogs#home"

  get "enter" => 'static_pages#enter'
  get "welcome" => 'static_pages#welcome'
  get "about" => 'static_pages#about'
  get "muffin" => 'static_pages#muffin'
  get "munchkin" => 'static_pages#munchkin'
  get "new_entry" => 'blogs#new'
  get "pictures" => 'pictures#index'
  get '/pictures/:id' => 'pictures#show', as: 'picture'

  resources :blogs do
    resources :comments
  end

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  default_scope -> { order(event_date: :desc, created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates(:user_id, presence: true)
  validate(:check_muffin)
  validate(:check_munchkin)
  validates(:event_date, presence: true)
  validate(:is_future_today)
  validate(:picture_size)
  before_create :pic_orientation
  
  def same_day_blog
    Blog.where.not(picture: nil).where("event_date = ?", self.event_date)
  end
  
  def older
    if self.id == same_day_blog.last.id
      # If the record is on the last record on a given event_date,
      # the older record will be the first on the previous event_date.
      Blog.where.not(picture: nil).where("event_date < ?", 
                                          self.event_date).first
    else
      # If not, the next record will be the first on the previous created_at.
      same_day_blog.where("created_at < ?", self.created_at).first
    end
  end
  
  def newer   # The reverse of "older"
    if self.id == same_day_blog.first.id
      Blog.where.not(picture: nil).where("event_date > ?", 
                                           self.event_date).last
    else
      same_day_blog.where("created_at > ?", self.created_at).last
    end
  end
  
  private
  
    def pic_orientation
      if self.picture?
        img = MiniMagick::Image::read(picture)
        if img[:width] > img[:height]
          self.pic_horizontal = true
        end
      end
    end
  
    def check_muffin
      if blog_muffin.blank?
        errors.add(:base, "Muffin's thought is blank")
      end
      if blog_muffin.length > 1000
        errors.add(:base, "Muffin's thought is too long (Max 200 characters)")
      end
    end
    
    def check_munchkin
      if blog_munchkin.length > 1000
        errors.add(:base, "Munchkin's thought is too long (Max 200 characters)")
      end
    end
    
    def is_future_today
      if event_date
        if event_date > Date.today
          errors.add(:base, "Date should not be a future date")
        end
      end
    end
    
    def picture_size
      if picture.size > 4.megabytes
        errors.add(:base, "Upload size limited to 4MB")
      end
    end
    
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :admin_user, only: [:new, :create, :destroy]
  
  def home
    @blogs = Blog.all
    @random_blogs = Blog.where.not(picture: nil).sample(3)
    @recent_blogs = Blog.where.not(picture: nil).first(3)
  end
  
  def index
    @blogs = Blog.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @blog = current_user.blogs.build
  end
  
  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      flash[:success] = "Entry Saved"
      redirect_to blogs_path
    else
      render 'new'
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
  end
  
  def edit
    @blog = Blog.find(params[:id])
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(blog_params)
      flash[:success] = "Entry updated"
      redirect_to blog_path(@blog)
    else
      render 'edit'
    end
  end
  
  def destroy
    Blog.find(params[:id]).destroy
    flash[:success] = "Entry deleted"
    redirect_to blogs_path
  end
  
  private
  
    def blog_params
      params.require(:blog).permit(:blog_muffin, :blog_munchkin, 
                                   :event_date, :picture, :pic_horizontal,
                                   :remove_picture)
    end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="row middle">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@blog, html: {multipart: true}) do |f| %>
      <%= render 'shared/errors', object: f.object %>
      <div class="blog_form">
        <%= f.label :picture, "Picture Upload" %>
        <% if @blog.picture? %>
          <%= image_tag @blog.picture, size: "415x415", class: "crop" %>
          <span>
            Remove Picture
          </span>
          <%= f.check_box :remove_picture%>
          <br><br>
        <% else %>
          <div id="button_upload">
            <%= f.file_field :picture %>
          </div>
        <% end %>
        <%= f.label :event_date, "Event's Date" %>
        <div>
          <%= f.date_select :event_date, {order: [:month, :day, :year]} %>
          <br></br>
        </div>
        <%= f.label :blog_muffin, "Muffin's thought" %>
        <%= f.text_area :blog_muffin, class: "form_control" %>
        <%= f.label :blog_munchkin, "Munchkin's thought"%>
        <%= f.text_area :blog_munchkin, class: "form_control" %>
        <%= f.submit yield(:button), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/edit.html.erb
<% provide(:title, "Edit Blog Entry") %>
<% provide(:button, "Edit") %>

<%= render 'form' %>

app/views/blogs/home.html.erb
<div class="home_container">
  <div class="random_and_recent_box">
    <div class="feature_header">
      Feature Entries
    </div>
    <div class="random_container">
      <% if @random_blogs.first.nil? %>
        <figure>
          
        </figure>
      <% elsif @random_blogs.first.pic_horizontal %>
        <figure>
          <%= link_to blog_path(@random_blogs.first) do %>
            <%= image_tag(@random_blogs.first.picture, size: "725x408", 
                          class: "picture_padding") %>
            <%= content_tag :figcaption, @random_blogs.first.event_date, 
                            class: "random_figcaption_large_landscape" %>
          <% end %>
        </figure>
        <% @random_blogs.shift %>
        <ul>
          <% @random_blogs.each do |blog| %>
            <li class="float_left">
              <figure>
                <%= link_to blog_path(blog) do %>
                  <%= image_tag(blog.picture, size: "360x272", 
                                class: "crop picture_padding_random") %>
                  <%= content_tag :figcaption, blog.event_date, 
                                  class: "random_figcaption_landscape" %>
                <% end %>
              </figure>
            </li>
          <% end %>
        </ul>
      <% else %>
        <figure>
          <%= link_to blog_path(@random_blogs.first) do %>
            <%= image_tag(@random_blogs.first.picture, size: "385x685", 
                          class: "picture_padding_float_left") %>
            <%= content_tag :figcaption, @random_blogs.first.event_date, 
                            class: "random_figcaption_large_portriat" %>
          <% end %>
        </figure>
        <% @random_blogs.shift %>
        <ul>
          <% @random_blogs.each do |blog| %>
            <li class="no_float">
              <%= link_to blog_path(blog) do %>
                <%= image_tag(blog.picture, size: "335x335", class: "crop") %>
                <%= content_tag :figcaption, blog.event_date, 
                                class: "random_figcaption_portriat" %>
              <% end %>
            </li>
        <% end %>
        </ul>
        
      <% end %>
    </div>
    <div class="recent_header">
      Recent Entries
    </div>
    <div class="recent_container">
      <div class="recent_container_pictures">
        <ul>
          <% @recent_blogs.each do |blog| %>
            <li>
              <div>
                <figure>
                  <%= link_to blog_path(blog) do %>
                    <%= image_tag(blog.picture, size: "235x235", 
                                                class: "crop") %>
                    <%= content_tag :figcaption, blog.event_date, 
                                                 class: "recent_figcaption" %>
                  <% end %>
                </figure>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="all_entries_box">
    <div class="all_entries_heading">
      All Entries
    </div>
    <div class="all_entries">
      <ol>
        <% @blogs.each do |blog| %>
          <li>
            <%= link_to blog.event_date, blog_path(blog), 
                                         class: "orange_link" %>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<div >
  <div class="middle" data-no-turbolink>
    <% n = 0 %>
    <% @blogs.each do |blog| %>
      <ul>
        <li>
          <% if blog.pic_horizontal == true || !blog.picture? %>
            <div>
              <div class="blog_date">
                <h3><%= blog.event_date.try(:strftime, "%B %d, %Y" ) %></h3>
              </div>
              <% if blog.picture? %>
                <div class="add_margin_bottom">
                  <%= link_to image_tag(blog.picture.url, width: "889"), 
                                        blog_path(blog) %>
                </div>
              <% end %>
              <div class="comment_and_button">
                <div class="blog_comments">
                  <div class="blog_heading">
                    <span id="heading<%= n %>">
                      Muffin's Thought
                    </span>
                    <% if !blog.blog_munchkin.blank? %>
                      <button class="clicky_blog"
                              data-blogid="blog<%= n %>"
                              data-headingid="heading<%= n %>"
                              data-thoughtid="thought<%= n %>"
                              data-muffin="<%= blog.blog_muffin %>"
                              data-munchkin="<%= blog.blog_munchkin %>"
                              data-click-state="muffin"
                              id="thought<%= n %>">
                        Go to Munchkin's World
                      </button>
                    <% end %>
                  </div>
                  <div class="comment" id="blog<%= n %>" 
                       data-comments="<%= blog_path(blog) %> #load_comments">
                    <%= blog.blog_muffin %>
                  </div>
                </div>
                <% if current_user && current_user.admin %>
                  <div class="edit_delete center">
                    <%= link_to "Edit", edit_blog_path(blog), 
                                        class: "orange_link" %>
                    |
                    <%= link_to "Delete", blog, method: :delete, 
                                          data: { confirm: "Are you sure?"},
                                          class: "orange_link" %>
                  </div>
                <% end %>
                <div class="fb_comments_box">
                  <div id="comments_landscape<%= n %>" 
                       class="fb_comments_container_landscape_index 
                              fb_comments_index<%= n %>" 
                       data-path=<%= "http://rails-tutorial-evilmuffin.c9users.io" + 
                                     blog_path(blog) %>></div>
                  <!-- use my c9.io path because fb-comments blocks herokuapp.com -->
                </div>
              </div>
            </div>
            <div class="blog_divider"></div>
          <% else %>
            <div>
              <div class="blog_date">
                <h3><%= blog.event_date.try(:strftime, "%B %d, %Y" ) %></h3>
              </div>
            </div>
            <div class="image_vertical">
              <%= link_to image_tag(blog.picture.url, height: "870" ), 
                                    blog_path(blog) %>
            </div>
            <div class="blog_vertical">
              <div class="comment_and_button fixed_height">
                <div class="blog_comments">
                  <div class="blog_heading">
                    <span id="heading<%= n %>">
                      Muffin's Thought
                    </span>
                    <% if !blog.blog_munchkin.blank? %>
                      <button class="clicky_blog"
                              data-blogid="blog<%= n %>"
                              data-headingid="heading<%= n %>"
                              data-thoughtid="thought<%= n %>"
                              data-muffin="<%= blog.blog_muffin %>"
                              data-munchkin="<%= blog.blog_munchkin %>"
                              data-click-state="muffin"
                              id="thought<%= n %>">
                        Go to Munchkin's World
                      </button>
                    <% end %>
                  </div>
                  <div class="comment" id="blog<%= n %>" 
                       data-comments="<%= blog_path(blog) %> #load_comments">
                    <%= blog.blog_muffin %>
                  </div>
                </div>
                <% if current_user && current_user.admin %>
                  <div class="edit_delete center">
                    <%= link_to "Edit", edit_blog_path(blog), 
                                        class: "orange_link" %>
                    |
                    <%= link_to "Delete", blog, method: :delete, 
                                          data: { confirm: "Are you sure?"},
                                          class: "orange_link" %>
                  </div>
                <% end %>
                <div class="fb_comments_box">
                  <div id="comments_portrait<%= n %>" 
                       class="fb_comments_container_portrait_index 
                               fb_comments_index<%= n %>" 
                       data-path=<%= "http://rails-tutorial-evilmuffin.c9users.io" + 
                                     blog_path(blog) %>></div>
                 <!-- use my c9.io path because fb-comments blocks herokuapp.com -->
                </div>
            </div>
            <div class="blog_divider"></div>
          <% end %>
        </li>
      </ul>
      <% n += 1 %>
    <% end %>
    
    <%= will_paginate @blogs, page_links: false, previous_label: "Newer", 
                              next_label: "Older", class: "center" %>
  </div>
</div>


<script>
  $(document).ready(function(){
    for (var counter = 0; counter < 5; counter ++ ) {
      var path = $(".fb_comments_index" + counter).data('path');
      $("#comments_landscape" + counter).html("<div class='fb-comments' data-href=" + path + " data-num-posts='5' data-width='830px'></div>");
      $("#comments_portrait" + counter).html("<div class='fb-comments' data-href=" + path + " data-num-posts='5' data-width='330px'></div>");
      /*
      $("#comments" + counter).load($("#blog" + counter).data('comments'));
      */
    };
  });
</script>

app/views/blogs/new.html.erb
<% provide(:title, "New Blog Entry") %>
<% provide(:button, "New Entry") %>

<%= render 'form' %>

app/views/blogs/show.html.erb
<% provide(:title, "Entries") %>
<% provide(:button, "Enter") %>
<div class="blog_show">
  <% if @blog.pic_horizontal == true || !@blog.picture? %>
    <div class="blog_date">
      <h3><%= @blog.event_date.try(:strftime, "%B %d, %Y" ) %></h3>
    </div>
    <% if @blog.picture? %>
      <div>
        <%= link_to image_tag(@blog.picture.url, width: "889"), 
                              picture_path(@blog) %>
      </div>
    <% end %>
    <div class="comment_and_button">
      <div class="blog_comments">
        <div class="blog_heading" id="muffins_thought_heading">
          Muffin's Thought
        </div>
        <div class="comment add_margin_bottom_small" id="muffins_thought_comment">
          <%= @blog.blog_muffin %>
        </div>
        <% if !@blog.blog_munchkin.empty? %>
          <div class="blog_heading_gray" id="munchkins_thought_heading">
            Munchkin's World
          </div>
          <div class="comment_gray" id="munchkins_thought_comment">
            <%= @blog.blog_munchkin %>
          </div>
        <% end %>
      </div>
      <% if current_user && current_user.admin %>
        <div class="edit_delete center">
          <%= link_to "Edit", edit_blog_path(@blog), 
                              class: "orange_link" %>
          |
          <%= link_to "Delete", @blog, method: :delete, 
                                data: { confirm: "Are you sure?"},
                                class: "orange_link" %>
        </div>
      <% end %>
      <div class="blog_comments" id="load_comments">
        <div class="fb_comments_container_landscape">
          <div class="fb-comments" 
               data-href="<%= "http://rails-tutorial-evilmuffin.c9users.io" + 
               request.path %>" data-width="830px" data-numposts="5">
          </div>
          <!-- use my c9.io path because fb-comments blocks herokuapp.com -->
        </div>
        <!--
        <div class="blog_heading">
          Comments
          <span><%= " | " if !current_user %></span>
          <span class="small_font">
            <%= "To comment, sign in with #{ 
                  link_to image_tag('facebook.png', size: '15x15'), 
                  '/auth/facebook'
                }".html_safe if !current_user %>
          </span> 
        </div>
        <% if !@blog.comments.empty? %>
          <% @blog.comments.each do |comment| %>
            <div class="comments_display">
              <%= image_tag(comment.user.avatar, size: "30x30") %>
              <span class="commenter">
                <%= link_to comment.user.name, 
                    "https://www.facebook.com/#{comment.user.uid}", 
                    target: "blank", class: "orange_small_link_bold" %>:
              </span>
              <span class="timestamp">
                Comment posted <%= time_ago_in_words(comment.created_at) %>
              </span>
              <span class="comment_content"><%= comment.content %>
                <% if current_user && ( current_user?(comment.user) || current_user.admin ) %>
                  <span class="orange_text">(
                    <%= link_to "edit", edit_blog_comment_path(comment.blog, comment),
                                        class: "orange_small_link" %>
                    |
                    <%= link_to "delete", [comment.blog, comment],
                                          data: { confirm: "Are you sure?"},
                                          :method => :delete, 
                                          class: "orange_small_link" %>
                    )
                  </span>
                <% end %>
              </span>
            </div>
          <% end %>
        <% else %>
          <div class="comments_display">
            Be the first to comment!
          </div>
        <% end %>
        <% if current_user %>
          <div class="blog_heading add_margin_top">
            Add a Comment
          </div>
          <%= render "comments/form" %>
        <% end %>
        -->
      </div>
    </div>
    <div class="blog_divider"></div>
  <% else %>
    <div class="blog_date">
      <h3><%= @blog.event_date.try(:strftime, "%B %d, %Y" ) %></h3>
    </div>
    <div class="image_vertical">
      <%= link_to image_tag(@blog.picture.url, height: "870" ), 
                            picture_path(@blog) %>
    </div>
    <div class="blog_vertical">
      <div class="comment_and_button fixed_height">
        <div class="blog_comments">
          <div class="blog_heading" id="muffins_thought_heading">
            Muffin's Thought
          </div>
          <div class="comment add_margin_bottom_small" id="muffins_thought_comment">
            <%= @blog.blog_muffin %>
          </div>
          <% if !@blog.blog_munchkin.empty? %>
            <div class="blog_heading_gray" id="munchkins_thought_heading">
              Munchkin's World
            </div>
            <div class="comment_gray"% id="munchkins_thought_comment">
              <%= @blog.blog_munchkin %>
            </div>
          <% end %>
        </div>
        <% if current_user && current_user.admin %>
          <div class="edit_delete center">
            <%= link_to "Edit", edit_blog_path(@blog), 
                                class: "orange_link" %>
            |
            <%= link_to "Delete", @blog, method: :delete, 
                                  data: { confirm: "Are you sure?"},
                                  class: "orange_link" %>
          </div>
        <% end %>
        <div class="blog_comments" id="load_comments">
          <!--
          <div class="blog_heading">
            Comments
            <span><%= " | " if !current_user %></span>
            <span class="small_font">
              <%= "To comment, sign in with #{ 
                    link_to image_tag('facebook.png', size: '15x15'), 
                    '/auth/facebook'
                  }".html_safe if !current_user %>
            </span> 
          </div>
          -->
          <div class="fb_comments_container_portrait">
            <div class="fb-comments" 
                 data-href="<%= "http://rails-tutorial-evilmuffin.c9users.io" + 
                   request.path %>" data-width="330px" data-numposts="5">
            </div>
            <!-- use my c9.io path because fb-comments blocks herokuapp.com -->
          </div>
          <!--
          <% if !@blog.comments.empty? %>
            <% @blog.comments.each do |comment| %>
              <div class="comments_display">
                <%= image_tag(comment.user.avatar, size: "30x30") %>
              <span class="commenter">
                <%= link_to comment.user.name, 
                    "https://www.facebook.com/#{comment.user.uid}", 
                    target: "blank", class: "orange_small_link_bold" %>:
              </span>
              <span class="timestamp">
                Comment posted <%= time_ago_in_words(comment.created_at) %>
              </span>
              <span class="comment_content"><%= comment.content %>
                <% if current_user && ( current_user?(comment.user) || current_user.admin ) %>
                  <span class="orange_text">(
                    <%= link_to "edit", edit_blog_comment_path(comment.blog, comment),
                                        class: "orange_small_link" %>
                    |
                    <%= link_to "delete", [comment.blog, comment],
                                          data: { confirm: "Are you sure?"},
                                          :method => :delete, 
                                          class: "orange_small_link" %>
                    )
                  </span>
                <% end %>
              </span>
              </div>
            <% end %>
          <% else %>
            <div class="comments_display">
              Be the first to comment!
            </div>
          <% end %>
          <% if current_user %>
            <div class="blog_heading add_margin_top">
              Add a Comment
            </div>
            <%= render "comments/form" %>
          <% end %>
          -->
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    var mth = "#muffins_thought_heading";
    var mtc = "#muffins_thought_comment";
    var mkth = "#munchkins_thought_heading";
    var mktc = "#munchkins_thought_comment";
    var bhg = "blog_heading_gray";
    var bh = "blog_heading";
    var cmg = "comment_gray";
    var cm = "comment";
    function switchClass(id, class_in, class_out){
      $(id).addClass(class_in);
      $(id).removeClass(class_out);
    };
    function muffinSwitchClass(){
      switchClass(mth, bhg, bh);
      switchClass(mtc, cmg, cm);
      switchClass(mkth, bh, bhg);
      switchClass(mktc, cm, cmg);
    };
    function munchkinSwitchClass(){
      switchClass(mth, bh, bhg);
      switchClass(mtc, cm, cmg);
      switchClass(mkth, bhg, bh);
      switchClass(mktc, cmg, cm);
    };
    $(mkth).mouseover(function(){
      muffinSwitchClass();
    });
    $(mktc).mouseover(function (){
      muffinSwitchClass();
    });
    $(mth).mouseover(function (){
      munchkinSwitchClass();
    });
    $(mtc).mouseover(function (){
      munchkinSwitchClass();
    });
  });
</script>