config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root "blogs#home"

  get "enter" => 'static_pages#enter'
  get "welcome" => 'static_pages#welcome'
  get "about" => 'static_pages#about'
  get "muffin" => 'static_pages#muffin'
  get "munchkin" => 'static_pages#munchkin'
  get "new_entry" => 'blogs#new'
  get "pictures" => 'pictures#index'
  get '/pictures/:id' => 'pictures#show', as: 'picture'

  resources :blogs do
    resources :comments
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  
  def index
    @blogs = Blog.where.not(picture: nil).paginate(page: params[:page], per_page: 9)
  end
  
  def show
    @blog = Blog.find(params[:id])

    if @blog == Blog.where.not(picture: nil).last
      @older_blog = @blog   # Place holder code for now
    else
      @older_blog = @blog.older
    end
    
    if @blog == Blog.where.not(picture: nil).first
      @newer_blog = @blog   # Place holder code for now
    else
      @newer_blog = @blog.newer
    end
  end
  
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/index.html.erb
<div class="middle center">
  <% if @blogs.any? %>
    <% @blogs.each do |blog| %>
      <span>
        <%= link_to image_tag(blog.picture, size: "287x287", class: "crop"), picture_path(blog)  %>
      </span>
    <% end %>
  <% end %>
  <%= will_paginate @blogs, page_links: false, previous_label: "Newer", 
                            next_label: "Older", class: "center" %>
</div>

app/views/pictures/show.html.erb
<% new_path = picture_path(@newer_blog) %>
<% old_path = picture_path(@older_blog) %>
<div class="picture_show">
  <% if @blog.pic_horizontal %>
    <div class="relative_position">
      <%= image_tag @blog.picture, :usemap => "#landscape" %>
      <map name="landscape">
        <area shape="rect" coords="0,0,195,500" class="pointer"
              id="newer">
        <area shape="rect" coords="695,0,889,500" class="pointer"
              id="older">
      </map>
      <div id="newer_link" data-path="<%= new_path %>">
        🢔
      </div>
      <div id="older_link" data-path="<%= old_path %>">
        🢖
      </div>
    </div>
  <% else %>
    <div id="newer_portrait">
      <div id="newer_portrait_link" data-path="<%= new_path %>">
        <div class="center portrait_pointer">
          🢔
        </div>
      </div>
    </div>
    <div class="picture_show_vertical" >
      <%= image_tag @blog.picture %>
    </div>
    <div id="older_portrait">
      <div id="older_portrait_link" data-path="<%= old_path %>">
        <div class="center portrait_pointer">
          🢖
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    
    function poofIn(id, timer){
      $(id).fadeIn(timer);
    };
    
    function showLink(id1, id2, timer){
      $(id1).mouseover(function(){
        poofIn(id2, timer);
      });
      $(id2).mouseout(function(){
        $(this).fadeOut(timer);
      });
    };
    
    function loadPage(id){
      $(id).click(function(){
      window.location = $(this).data('path');
      });
    };
    
    showLink("#newer", "#newer_link", 100);
    showLink("#older", "#older_link", 100);
    showLink("#newer_portrait", "#newer_portrait_link", 100);
    showLink("#older_portrait", "#older_portrait_link", 100);
    loadPage("#newer_link");
    loadPage("#older_link");
    loadPage("#newer_portrait_link");
    loadPage("#older_portrait_link");
    
  });
</script>