config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]

  root "blogs#home"

  get "enter" => 'static_pages#enter'
  get "welcome" => 'static_pages#welcome'
  get "about" => 'static_pages#about'
  get "muffin" => 'static_pages#muffin'
  get "munchkin" => 'static_pages#munchkin'
  get "new_entry" => 'blogs#new'
  get "pictures" => 'pictures#index'
  get '/pictures/:id' => 'pictures#show', as: 'picture'

  resources :blogs do
    resources :comments
  end

end

app/views/layouts/_footer.html.erb
<footer class="container navbar-fixed-bottom">
  <div id="footer_style">
    <div id="footer_links">
      <ul>
        <li>
          <%= link_to "About", about_path %>
        </li>
        <li>
          <%= link_to "LinkedIn", 
                      "https://www.linkedin.com/in/au-lee-216779120", 
                      :target => "blank" %>
        </li>
        <li>
          <%= link_to "Source", 
                      "https://bitbucket.org/Evilmuffin/muffin_blog/src", 
                      :target => "blank" %>
        </li>
        <li>
          <%= link_to "Contact", "mailto:leea75hhh@gmail.com", :target => "blank" %>
        </li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed-top">
  <div id="header_style" class="container">
    <h1>
      <font color="red">Evil</font><font color="black">muffin 
      <span class="text_stroke">&&</span> the</font> Munchkin 
      <font color="black">from</font> <font color="red">Hell</font> 
    </h1>
  </div>

</header>

app/views/layouts/_left_panel.html.erb
<div class="clicky">
  <!--
  <ul>
    <div class="button_space"><br></div>
    <li>
      <div id="home_button_space" class="button_out">
        <%= link_to "Home", root_path, data: { no_turbolink: true }, 
                          class: "btn btn-primary", id: "home_button" %>
      </div>
    </li>
    <li>
      <div id="muffin_button_space" class="button_out">
        <%= link_to "Evilmuffin", muffin_path, class: "btn btn-primary",
                                               id: "muffin_button" %>
      </div>
    </li>
    <li>
      <div id="munchkin_button_space" class="button_out">
        <%= link_to "Munchkin", munchkin_path, class: "btn btn-primary",
                                               id: "munchkin_button"%>
      </div>
    </li>
    <li>
      <div id="picture_button_space" class="button_out">
        <%= link_to "Pictures", pictures_path, class: "btn btn-primary", 
                                     id: "picture_button" %>
      </div>
    </li>
    <% if current_user && current_user.admin %>
      <div id="entry_button_space" class="button_out">
        <%= link_to "New Entry", new_entry_path, class: "btn btn-primary",
                                                 id: "entry_button"%>
      </div>
    <% end %>
    <div class="button_space"><br></div>
  </ul>
  
  <div class="sign_in_out">
    <ul>
      <div class="button_space"><br></div>
      <% if current_user %>
        <li>
          <div id="sign_in_out_button_space" class="button_out">
            <%= link_to "Sign out", signout_path, 
                                    data: { no_turbolink: true },
                                    class: "btn btn-primary",
                                    id: "sign_in_out_button" %>
          </div>
        </li>
      <% else %>
        <li>
          <div id="sign_in_out_button_space" class="button_out">
            <%= link_to "Sign in", "/auth/facebook", 
                                   class: "btn btn-primary",
                                   id: "sign_in_out_button" %>
          </div>
        </li>
      <% end %>
      <div class="button_space"><br></div>
    </ul>
  </div>
  -->
</div>

<!--
<script>
  function buttonOver(){
    $(this).addClass("button_over");
    $(this).removeClass("button_out");
  };
  
  function buttonOut(){
    $(this).addClass("button_out");
    $(this).removeClass("button_over");
  };
  
  $(document).ready(function(){
    $('#home_button_space').mouseover(buttonOver);
    $('#home_button_space').mouseout(buttonOut);
    $('#muffin_button_space').mouseover(buttonOver);
    $('#muffin_button_space').mouseout(buttonOut);
    $('#munchkin_button_space').mouseover(buttonOver);
    $('#munchkin_button_space').mouseout(buttonOut);
    $('#picture_button_space').mouseover(buttonOver);
    $('#picture_button_space').mouseout(buttonOut);
    $('#entry_button_space').mouseover(buttonOver);
    $('#entry_button_space').mouseout(buttonOut);
    $('#sign_in_out_button_space').mouseover(buttonOver);
    $('#sign_in_out_button_space').mouseout(buttonOut);
  });
</script>
-->

app/views/layouts/_navbar.html.erb
<div class="container main_navbar navbar-fixed-top">
  <ul>
    <li id="home_button">
      <%= link_to "Home", root_path, data: { no_turbolink: true } %>
    </li>
    <li id="muffin_button">
      <%= link_to "Evilmuffin", muffin_path %>
    </li>
    <li id="munchkin_button">
      <%= link_to "Munchkin", munchkin_path %>
    </li>
    <li class="dropdown" id="blog_button">
      <a href="#" class="dropbtn">Blogs</a>
      <div class="dropdown-content">
        <%= link_to "Entries", blogs_path, data: { no_turbolink: true } %>
        <%= link_to "Pictures", pictures_path %>
        <% if current_user && current_user.admin %>
          <%= link_to "New", new_entry_path %>
        <% end %>
      </div>
    </li>
    <% if current_user %>
      <li>
        <%= link_to "Sign out", signout_path, data: { no_turbolink: true }%>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign in", "/auth/facebook" %>
      </li>
    <% end %>
  </ul>
  <div class="sign_in_as">
    <% if current_user %>
      <span class="red_text add_margin_right">
        Signed in as:
      </span>
      <span class="white_text add_margin_right">
        <%= image_tag(current_user.avatar, size: "30x30") %>
      </span>
    <% end %>
  </div>
  <div class="icons">
    <ul>
      <li>
        <a href=<%= about_path %> target="blank">
          <i class="fa fa-info-circle" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="https://www.linkedin.com/in/au-lee-216779120" target="blank">
          <i class="fa fa-linkedin-square" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="https://bitbucket.org/Evilmuffin/muffin_blog/src" target="blank">
          <i class="fa fa-bitbucket-square" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="mailto:leea75hhh@gmail.com" target="blank">
          <i class="fa fa-envelope-square" aria-hidden="true"></i>
        </a>
      </li>
    </ul>
    <div class="fb_like_and_share">
      <div class="fb-like" data-href="http://muffin-blog.herokuapp.com/" 
                           data-layout="button_count" 
                           data-action="like" 
                           data-size="small" 
                           data-show-faces="false" 
                           data-share="true">
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    var path = window.location.pathname;
    function activeLink(id){
      $(id).toggleClass("active_button");
    };
    if (path == "/") 
      activeLink("#home_button");
    else if (path == "/muffin")
      activeLink("#muffin_button");
    else if (path == "/munchkin")
      activeLink("#munchkin_button");
    else if (path.indexOf("/pictures") >= 0)
      activeLink("#blog_button");
    else if (path.indexOf("/blogs") >=0 )
      activeLink("#blog_button");
    else if (path == "/new_entry")
      activeLink("#blog_button");
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                               'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
        </script>
    <![endif]-->
    <!--%= favicon_link_tag 'favicon.ico' % -->
    <meta name="viewport"       content="width=device-width, initial-scale=1" />
    <meta property="og:url"     content="http://muffin-blog.herokuapp.com/" />
    <meta property="og:type"    content="website" />
    <meta property="og:title"   content="Evilmuffin && the Munchkin from Hell" />
    <meta property="og:description"   content="The life of Evilmuffin his little Munchkin" />
    <meta property="og:image"         content=<%= asset_path("muffin.jpg") %> />
    <meta property="fb:app_id" content="1700384183556431" />
    
    <script src="https://use.fontawesome.com/741df4f831.js"></script>
  </head>
  <body>
    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7&appId=1700384183556431";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
      
    <%= render 'layouts/header' %>
    <%= render 'layouts/navbar' %>
    
    <div class="container" id=main_panel>
      

        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>

      
    </div>  
  
  </body>
</html>